Simplify use of user-defined flags.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/tools/make/trunk@17744 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -317,7 +317,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os ac_cv_library_combo CYGWIN RANLIB AR DLLTOOL ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S TAR CHOWN GNUSTEP_ROOT root_prefix MAKEFILES_SUFFIX HOST_INSTALL GNUSTEP_LOCAL_ROOT GNUSTEP_NETWORK_ROOT GNUSTEP_FLATTENED GNUSTEP_MULTI_PLATFORM BACKEND_BUNDLE EGREP objc_threaded ac_cv_objc_threaded AUTO_DEPENDENCIES OBJC_NO_IMPORT_FLAGS INCLUDE_FLAGS GNUSTEP_MOVE_OBSOLETE GNUSTEP_MAKE_VERSION GNUSTEP_MAKE_MAJOR_VERSION GNUSTEP_MAKE_MINOR_VERSION GNUSTEP_MAKE_SUBMINOR_VERSION clean_target_os clean_target_cpu clean_target_vendor LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os ac_cv_library_combo CYGWIN RANLIB AR DLLTOOL ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S TAR CHOWN GNUSTEP_ROOT root_prefix MAKEFILES_SUFFIX HOST_INSTALL GNUSTEP_LOCAL_ROOT GNUSTEP_NETWORK_ROOT GNUSTEP_FLATTENED GNUSTEP_MULTI_PLATFORM BACKEND_BUNDLE EGREP objc_threaded ac_cv_objc_threaded AUTO_DEPENDENCIES INCLUDES OBJC_NO_IMPORT_FLAGS GNUSTEP_MOVE_OBSOLETE GNUSTEP_MAKE_VERSION GNUSTEP_MAKE_MAJOR_VERSION GNUSTEP_MAKE_MINOR_VERSION GNUSTEP_MAKE_SUBMINOR_VERSION clean_target_os clean_target_cpu clean_target_vendor LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2529,6 +2529,7 @@ if test "$ac_cv_library_combo" = ""; then
   case "$host_os" in
     darwin*)   ac_cv_library_combo=apple-apple-apple ;;
     nextstep4) ac_cv_library_combo=nx-nx-nx          ;;
+    openstep4) ac_cv_library_combo=nx-nx-nx          ;;
     *)         ac_cv_library_combo=gnu-gnu-gnu       ;;
   esac
 fi
@@ -2548,19 +2549,14 @@ OBJC_RUNTIME_LIB=`echo $ac_cv_library_combo | awk -F- '{print $1}'`
 #--------------------------------------------------------------------
 # specific target_os options
 #--------------------------------------------------------------------
-INCLUDE_FLAGS=
+INCLUDES=
 case "$target_os" in
   freebsd* | openbsd* )
-	        INCLUDE_FLAGS="$INCLUDE_FLAGS -I/usr/local/include"
-		LIBS="$LIBS -L/usr/local/lib";;
-  netbsd*)	INCLUDE_FLAGS="$INCLUDE_FLAGS -I/usr/pkg/include"
-		LIBS="$LIBS -Wl,-R/usr/pkg/lib -L/usr/pkg/lib";;
+	        INCLUDES="-I/usr/local/include"
+		LDFLAGS="$LDFLAGS -L/usr/local/lib";;
+  netbsd*)	INCLUDES="-I/usr/pkg/include"
+		LDFLAGS="$LDFLAGS -Wl,-R/usr/pkg/lib -L/usr/pkg/lib";;
 esac
-# Save the user supplied CPPFLAGS so we can restore them later.
-user_CPPFLAGS="$CPPFLAGS"
-# This is just for configuring. Later, in config.make, INCLUDE_FLAGS
-# goes in CONFIG_SYSTEM_INCL and the original CPPFLAGS goes in unaltered
-CPPFLAGS="$CPPFLAGS $INCLUDE_FLAGS"
 
 #--------------------------------------------------------------------
 # Determine the host, build, and target systems
@@ -3305,9 +3301,9 @@ echo "${ECHO_T}$gs_cv_objc_libdir" >&6
 # The following are needed to compile the test programs
 if test "$gs_cv_objc_libdir" = "$GNUSTEP_LDIR"; then
   if test "$GNUSTEP_FLATTENED" = yes; then
-    OBJC_CPPFLAGS="$INCLUDE_FLAGS -I$prefix/Library/Headers"
+    OBJC_CPPFLAGS="$CPPFLAGS $INCLUDES -I$prefix/Library/Headers"
   else
-    OBJC_CPPFLAGS="$INCLUDE_FLAGS -I$prefix/Library/Headers/${ac_cv_library_combo}"
+    OBJC_CPPFLAGS="$CPPFLAGS $INCLUDES -I$prefix/Library/Headers/${ac_cv_library_combo}"
   fi
   OBJC_LDFLAGS="$LDFLAGS -L$gs_cv_objc_libdir"
 fi
@@ -4099,12 +4095,6 @@ fi;
 
 echo "$as_me:$LINENO: checking whether objc has thread support" >&5
 echo $ECHO_N "checking whether objc has thread support... $ECHO_C" >&6
-extra_LIBS=""
-case "${target_os}" in
-  solaris*)
-        extra_LIBS="-lposix4"
-        ;;
-esac
 saved_CFLAGS="$CFLAGS"
 saved_LIBS="$LIBS"
 CFLAGS="$CFLAGS -x objective-c -I$srcdir $OBJC_CPPFLAGS $OBJC_LDFLAGS"
@@ -4118,7 +4108,7 @@ if test "$OBJC_RUNTIME_LIB" = "apple"; then
   CFLAGS="$CFLAGS -DNeXT_RUNTIME"
 fi
 if test "$OBJC_THREAD" != ""; then
-  LIBS="-lobjc $LIBS $OBJC_THREAD $extra_LIBS"
+  LIBS="-lobjc $LIBS $OBJC_THREAD"
   if test "$cross_compiling" = yes; then
   objc_threaded=""
 else
@@ -4142,7 +4132,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  objc_threaded="$OBJC_THREAD $extra_LIBS"
+  objc_threaded="$OBJC_THREAD"
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
@@ -4301,7 +4291,7 @@ fi
   fi
 elif test "$MINGW32" = yes; then
   # Mingw doesn't need anything extra for threads
-  LIBS="-lobjc $LIBS $extra_LIBS"
+  LIBS="-lobjc $LIBS"
   if test "$cross_compiling" = yes; then
   objc_threaded="works"
 else
@@ -4337,7 +4327,7 @@ fi
 rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 else
-  LIBS="-lobjc $LIBS $extra_LIBS"
+  LIBS="-lobjc $LIBS"
   if test "$cross_compiling" = yes; then
   objc_threaded=""
 else
@@ -4373,7 +4363,7 @@ fi
 rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
   if test x"$objc_threaded" = x""; then
-    LIBS="-lobjc $saved_LIBS -lpthread $extra_LIBS"
+    LIBS="-lobjc $saved_LIBS -lpthread "
     if test "$cross_compiling" = yes; then
   objc_threaded=""
 else
@@ -4397,7 +4387,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  objc_threaded="-lpthread $extra_LIBS"
+  objc_threaded="-lpthread"
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
@@ -4410,7 +4400,8 @@ rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext 
 fi
   fi
   if test x"$objc_threaded" = x""; then
-    LIBS="-lobjc $saved_LIBS -lthread $extra_LIBS"
+    # Solaris, OpenBSD/sparc
+    LIBS="-lobjc $saved_LIBS -lpthread -lposix4"
     if test "$cross_compiling" = yes; then
   objc_threaded=""
 else
@@ -4434,7 +4425,44 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  objc_threaded="-lthread $extra_LIBS"
+  objc_threaded="-lpthread -lposix4"
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+objc_threaded=""
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+  fi
+  if test x"$objc_threaded" = x""; then
+    LIBS="-lobjc $saved_LIBS -lthread "
+    if test "$cross_compiling" = yes; then
+  objc_threaded=""
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "config_thread.m"
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  objc_threaded="-lthread"
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
@@ -4454,7 +4482,7 @@ if test x"$objc_threaded" = x""; then
 echo "${ECHO_T}no" >&6
 else
   if test x"$objc_threaded" = x"works"; then
-    objc_threaded="$extra_LIBS"
+    objc_threaded=""
   fi
   echo "$as_me:$LINENO: result: yes: $objc_threaded" >&5
 echo "${ECHO_T}yes: $objc_threaded" >&6
@@ -4501,6 +4529,7 @@ fi
 
 
 
+
 #---------------------------------------------------------------------
 # Enable/disable warnings for deprecated #import directive as required
 #---------------------------------------------------------------------
@@ -4525,9 +4554,6 @@ echo "${ECHO_T}$ac_cv_import" >&6
 if test "$ac_cv_import" = "yes"; then
   OBJC_NO_IMPORT_FLAGS=-Wno-import;
 fi
-
-
-CPPFLAGS="$user_CPPFLAGS"
 
 
 #--------------------------------------------------------------------
@@ -5267,8 +5293,8 @@ s,@EGREP@,$EGREP,;t t
 s,@objc_threaded@,$objc_threaded,;t t
 s,@ac_cv_objc_threaded@,$ac_cv_objc_threaded,;t t
 s,@AUTO_DEPENDENCIES@,$AUTO_DEPENDENCIES,;t t
+s,@INCLUDES@,$INCLUDES,;t t
 s,@OBJC_NO_IMPORT_FLAGS@,$OBJC_NO_IMPORT_FLAGS,;t t
-s,@INCLUDE_FLAGS@,$INCLUDE_FLAGS,;t t
 s,@GNUSTEP_MOVE_OBSOLETE@,$GNUSTEP_MOVE_OBSOLETE,;t t
 s,@GNUSTEP_MAKE_VERSION@,$GNUSTEP_MAKE_VERSION,;t t
 s,@GNUSTEP_MAKE_MAJOR_VERSION@,$GNUSTEP_MAKE_MAJOR_VERSION,;t t
