better error logging
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/tools/make/trunk@32206 72102866-910b-0410-8b05-ffd578937521

diff --git a/TestFramework/gnustep-tests b/TestFramework/gnustep-tests
--- a/TestFramework/gnustep-tests
+++ b/TestFramework/gnustep-tests
@@ -221,6 +221,10 @@ then
     run_test_file
     if [ "$RUNEXIT" != "0" ]
     then
+      if [ "$RUNEXIT" != "2" ]
+      then
+        echo "Failed file:      $TESTFILE" >&2
+      fi
       break
     fi
   done
@@ -266,6 +270,10 @@ else
       run_test_file
       if [ "$RUNEXIT" != "0" ]
       then
+        if [ "$RUNEXIT" != "2" ]
+        then
+          echo "Failed file:      $TESTFILE" >&2
+        fi
         break
       fi
     done
