furthr test framework improvements
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/tools/make/trunk@32181 72102866-910b-0410-8b05-ffd578937521

diff --git a/TestFramework/gnustep-tests b/TestFramework/gnustep-tests
--- a/TestFramework/gnustep-tests
+++ b/TestFramework/gnustep-tests
@@ -41,7 +41,7 @@ if test -z "$GNUSTEP_MAKEFILES"; then
   fi
 fi
 
-GSCLEAN=NO
+GSTESTMODE=normal
 
 # Argument checking
 while test $# != 0
@@ -49,7 +49,7 @@ do
   gs_option=
   case $1 in
     --clean)
-      GSCLEAN=YES
+      GSTESTMODE=clean
       ;;
     --documentation)
       echo
@@ -62,6 +62,9 @@ do
       cat $GNUSTEP_MAKEFILES/TestFramework/README
       exit 0
       ;;
+    --failfast)
+      GSTESTMODE=failfast
+      ;;
     --help | -h)
       echo
       echo "$0: Script to run the GNUstep testsuite"
@@ -69,6 +72,7 @@ do
       echo "Runs the specified tests, or any in subdirectories of the"
       echo "current directory if no arguments are given."
       echo "Use 'gnustep-tests --documentation' for full details."
+      echo "Use 'gnustep-tests --failfast' to stop at the first failure."
       echo "Use 'gnustep-tests --clean' to remove old logs and leftover files."
       echo
       echo "Interpreting the output"
@@ -78,20 +82,6 @@ do
       echo "software being tested, or a problem in the test itself. Either"
       echo "way, you should try to fix the problem and provide a patch, or"
       echo "at least report it at: https://savannah.gnu.org/bugs/?group=gnustep"
-      echo
-      echo "After the listing of any failures is a summary of counts of events:"
-      echo "COMPLETED:   The number of separate test files which were run."
-      echo "COMPILEFAIL: The number of separate test files which did not start."
-      echo "ABORTED:     The number of separate test files which failed to run."
-      echo "DASHED:      The number of hopes dashed ... tests which did not"
-      echo "             pass, but which were not expected to pass (new code"
-      echo "             beign worked on etc)."
-      echo "FAIL:        The number of individual tests failed"
-      echo "PASS:        The number of individual tests passed"
-      echo "UNRESOLVED:  The number of unresolved tests ... tests which have"
-      echo "             been omitted because of an earlier failure etc."
-      echo "UNSUPPORTED: The number of unsupported tests ... those for features"
-      echo "             which work on some platforms, but not on yours."
       echo
       exit 0
       ;;
@@ -144,32 +134,62 @@ then
 fi
 
 CWD=`pwd`
-TOP=$GNUSTEP_MAKEFILES/TestFramework
-export TOP
-RUNCMD=$TOP/runtest.sh
-cd $CWD
+OWD=
+RUNCMD=$GNUSTEP_MAKEFILES/TestFramework/runtest.sh
+RUNEXIT=0
 
 run_test_file ()
 {
-  echo >> $CWD/tests.log
-  echo Testing $TESTFILE... >> $CWD/tests.log
-  echo >> $CWD/tests.sum
+  sub=`dirname $TESTFILE`
+  if [ "x$OWD" != "x$sub" ]
+  then
+    OWD=$sub
+    if [ "$GSTESTMODE" = "clean" ]
+    then
+      echo "--- Cleaning tests in $sub ---"
+      rm -rf $sub/GNUmakefile.tmp $sub/obj $sub/core
+      rm -rf $sub/tests.tmp $sub/tests.sum.tmp
+      rm -rf $sub/tests.log $sub/tests.sum
+      rm -rf $sub/oldtests.log $sub/oldtests.sum
+    else
+      echo "--- Running tests in $sub ---"
+      echo "--- Running tests in $sub ---" >> $CWD/tests.log
+      if [ -r $dir/URGENT ]
+      then
+	cat $dir/URGENT
+	cat $dir/URGENT >> $CWD/tests.log
+      fi
+      if [ -r $dir/README ]
+      then
+	cat $dir/README >> $CWD/tests.log
+      fi
+    fi
+  fi
 
-  # Run the test. Log everything to a temporary file.
-  $RUNCMD $run_args $TESTFILE > $CWD/tests.tmp 2>&1
+  if [ "$GSTESTMODE" != "clean" ]
+  then
+    echo >> $CWD/tests.log
+    echo Testing $TESTFILE... >> $CWD/tests.log
+    echo >> $CWD/tests.sum
 
-  # Add the information to the detailed log.
-  cat $CWD/tests.tmp >> $CWD/tests.log
+    # Run the test. Log everything to a temporary file.
+    export GSTESTMODE
+    $RUNCMD $run_args $TESTFILE > $CWD/tests.tmp 2>&1
+    RUNEXIT=$?
 
-  # Extract the summary information and add it to the summary file.
-  grep "^\(Passed test\|Failed test\|Uncompiled file\|Completed file\|Aborted file\|Dashed hope\|Unresolved set\|Unsupported set\):" $CWD/tests.tmp > $CWD/tests.sum.tmp
-  cat $CWD/tests.sum.tmp >> $CWD/tests.sum
+    # Add the information to the detailed log.
+    cat $CWD/tests.tmp >> $CWD/tests.log
 
-  # If there were failures or unresolved tests then report them...
-  if grep -L "^\(Uncompiled file\|Aborted file\|Unresolved set\|Failed test\):" $CWD/tests.sum.tmp > /dev/null; then
-    echo
-    echo $TESTFILE:
-    grep "^\(Uncompiled file\|Aborted file\|Unresolved set\|Failed test\):" $CWD/tests.sum.tmp
+    # Extract the summary information and add it to the summary file.
+    grep "^\(Passed test\|Failed test\|Failed build\|Completed file\|Failed file\|Dashed hope\|Failed set\|Skipped set\):" $CWD/tests.tmp > $CWD/tests.sum.tmp
+    cat $CWD/tests.sum.tmp >> $CWD/tests.sum
+
+    # If there were failures or unresolved tests then report them...
+    if grep -L "^\(Failed build\|Failed file\|Failed set\|Failed test\):" $CWD/tests.sum.tmp > /dev/null; then
+      echo
+      echo $TESTFILE:
+      grep "^\(Failed build\|Failed file\|Failed set\|Failed test\):" $CWD/tests.sum.tmp
+    fi
   fi
 }
 
@@ -184,67 +204,69 @@ then
   mv tests.sum oldtests.sum
 fi
 
-if [ x"$GSCLEAN" = xYES ]
-then
-  rm -f oldtests.log
-  rm -f oldtests.sum
-fi
-
 if [ x"$TESTDIRS" = x ]
 then
-  if [ x"$GSCLEAN" = xYES ]
-  then
-    rm -rf obj
-  else
-    # Run specific individual test files.
-    for TESTFILE in $TESTS
-    do
-      run_test_file
-    done
-  fi
+  # Run specific individual test files.
+  for TESTFILE in $TESTS
+  do
+    run_test_file
+    if [ "$RUNEXIT" != "0" ]
+    then
+      break
+    fi
+  done
 else
   for dir in $TESTDIRS
   do
-    if [ x"$GSCLEAN" = xYES ]
+    TESTS=`find $dir -name \*.m | sort | sed -e 's/\(^\| \)X[^ ]*//g'`
+
+    # If there are no test files found, we need to print out a message
+    # at this level to let people know we processed the directory.
+    if [ "x$TESTS" = "x" ]
     then
-      echo "--- Cleaning tests in $dir ---"
-      cd $dir
-      if [ $TOP != `pwd` ]
+      if [ "$GSTESTMODE" = "clean" ]
       then
-        if [ -f GNUmakefile.tests ]
+        echo "--- Cleaning tests in $dir ---"
+      else
+        echo "--- Running tests in $dir ---"
+        echo "--- Running tests in $dir ---" >> $CWD/tests.log
+        if [ -r $dir/URGENT ]
+	then
+	  cat $dir/URGENT
+	  cat $dir/URGENT >> $CWD/tests.log
+	fi
+        if [ -r $dir/README ]
         then
-          $MAKE_CMD -f GNUmakefile.tests $MAKEFLAGS clean 2>&1 >> $CWD/tests.log
+	  cat $dir/README >> $CWD/tests.log
         fi
       fi
-      rm -rf obj
-      cd $CWD
-    else
-      echo "--- Running tests in $dir ---"
-      TESTS=`find $dir -name \*.m | sort | sed -e 's/\(^\| \)X[^ ]*//g'`
-      # If there is a GNUmakefile.tests in the directory, run it first.
-      # Unless ... we are at the top level, in which case that file is
-      # our template.
-      cd $dir
-      if [ $TOP != `pwd` ]
-      then
-        if [ -f GNUmakefile.tests ]
-        then
-          $MAKE_CMD -f GNUmakefile.tests $MAKEFLAGS debug=yes 2>&1
-        fi
-      fi
-      cd $CWD
-      for TESTFILE in $TESTS
-      do
-        run_test_file
-      done
     fi
+
+    # If there is a GNUmakefile.tests in the directory, run it first.
+    cd $dir
+    if [ -f GNUmakefile.tests ]
+    then
+      $MAKE_CMD -f GNUmakefile.tests $MAKEFLAGS debug=yes 2>&1
+    fi
+
+    # Now we process each test file in turn.
+    cd $CWD
+    for TESTFILE in $TESTS
+    do
+      run_test_file
+      if [ "$RUNEXIT" != "0" ]
+      then
+        break
+      fi
+    done
   done
 fi
 
-if [ x"$GSCLEAN" = xYES ]
+if [ "$GSTESTMODE" = "clean" ]
 then
-  rm -f tests.log
-  rm -f tests.sum
+  rm -f tests.tmp tests.sum.tmp
+  rm -f tests.log tests.sum
+  rm -f oldtests.log oldtests.sum
 else
   # Make some stats.
   if [ -r tests.sum ]
@@ -255,7 +277,9 @@ else
     # any summary with only a single result so the output is pretty.
     # Sort the resulting lines by number of each status with the most
     # common (hopefully passes) output first.
-    grep "^\(Passed test\|Failed test\|Uncompiled file\|Completed file\|Aborted file\|Dashed hope\|Unresolved set\|Unsupported set\):" tests.sum | cut -d: -f1 | sort | uniq -c | sed -e 's/.*/&s/' | sed -e 's/^\([^0-9]*1[^0-9].*\)s$/\1/' | sort -n -b -r > tests.tmp
+    # NB. we omit the 'Completed file' tests as uninteresting ... users
+    # generally only want to see the total pass count and any problems.
+    grep "^\(Passed test\|Failed test\|Failed build\|Failed file\|Dashed hope\|Failed set\|Skipped set\):" tests.sum | cut -d: -f1 | sort | uniq -c | sed -e 's/.*/&s/' | sed -e 's/^\([^0-9]*1[^0-9].*\)s$/\1/' | sort -n -b -r > tests.tmp
   else
     echo "No tests found." > tests.tmp
   fi
@@ -265,6 +289,84 @@ else
 
   echo
   cat tests.tmp
+  echo
+
+  grep -q "\(Failed set\|Failed sets\|Failed test\|Failed tests\|Failed build\|Failed build\|Failed file\|Failed files\)$" tests.tmp
+  if [ $? = 1 ]
+  then
+    echo "All OK!"
+
+    grep -q "\(Dashed hope\|Dashed hopes\)$" tests.tmp
+    if [ $? = 0 ]
+    then
+      echo 
+      echo "But we were hoping that even more tests might have passed if"
+      echo "someone had added support for them to the package.  If you"
+      echo "would like to help, please contact the package maintainer."
+    fi
+
+    grep -q "\(Skipped set\|Skipped sets\)$" tests.tmp
+    if [ $? = 0 ]
+    then
+      echo 
+      echo "Even though no tests failed, we had to skip some testing"
+      echo "due to lack of support on your system.  This might be because"
+      echo "some required software library was just not available when the"
+      echo "software was built (in which case you can install that library"
+      echo "and rebuild, then re-run the tests), or the required functions"
+      echo "may not be available on your operating system at all."
+      echo "If you would like to contribute code to add the missing"
+      echo "functionality, please contact the package maintainer."
+    fi
+
+  else
+    if [ "$GSTESTMODE" = "failfast" ]
+    then
+      exit 0
+    fi
+
+    grep -q "\(Failed build\|Failed build\)$" tests.tmp
+    if [ $? = 0 ]
+    then
+      echo
+      echo "Unfortunately we could not even compile all the test programs."
+      echo "This means that the test could not be run properly, and you need"
+      echo "to try to figure out why and fix it or ask for help."
+    fi
+
+    grep -q "\(Failed file\|Failed files\)$" tests.tmp
+    if [ $? = 0 ]
+    then
+      echo
+      echo "Some testing was abandoned when a test program aborted.  This is"
+      echo "generally a severe problem and may nean that the package is"
+      echo "completely unusuable.  You need to try to fix this and, if it's"
+      echo "not due to some problem on your system, please help by submitting"
+      echo "a patch (or at least a bug report) to the package maintainer."
+    fi
+
+    grep -q "\(Failed set\|Failed sets\)$" tests.tmp
+    if [ $? = 0 ]
+    then
+      echo
+      echo "Some set of tests failed.  This could well mean that a large"
+      echo "number of individual tests dis not pass and that there are"
+      echo "severe problems in the software."
+      echo "Please submit a patch to fix the problem or send a bug report to"
+      echo "the package maintainer."
+    fi
+
+    grep -q "\(Failed test\|Failed tests\)$" tests.tmp
+    if [ $? = 0 ]
+    then
+      echo
+      echo "One or more tests failed.  None of them should have."
+      echo "Please submit a patch to fix the problem or send a bug report to"
+      echo "the package maintainer."
+    fi
+  fi
+
+  echo
 fi
 
 # Delete the temporary file.
